#!/bin/bash

# https://github.com/z3ntu/halium-5.1-build-env
# docker build --tag android-k-build-env .

if ! systemctl is-active docker.service > /dev/null ; then
	sudo systemctl start docker.service
fi

docker run \
	--rm -it \
	--env USE_CCACHE=1 \
	--env CCACHE_DIR=/var/.ccache \
	--env CCACHE_MAXSIZE=50G \
	-v ~/works/android/lineage/cm-11.0:/var/android \
	-v ~/works/.ccache:/var/.ccache \
	android-k-build-env:latest
