#!/bin/bash

set -euo pipefail

CUR_DIR=$( pwd )

if [ ! -e ${CUR_DIR}/arch/arm/boot/zImage ]; then
  echo "no zImage found!";
  exit;
fi

if [ ! -d ${CUR_DIR}/releases/unpack ]; then
  echo "no working folder found!";
  exit;
fi

G_IDX=$( git rev-parse --verify --short HEAD )

cp ${CUR_DIR}/arch/arm/boot/zImage ${CUR_DIR}/releases/unpack/boot-zImage

d=`date +%d%b%Y_%H%M%S`

OUT="boot_${d}_${G_IDX}.img"

mkboot.1 -cf "${CUR_DIR}/releases/${OUT}" "${CUR_DIR}/releases/unpack"

if [ -z ${DISPLAY+x} ]; then
  echo -n "${CUR_DIR}/releases/${OUT}"
else
  echo -n "${CUR_DIR}/releases/${OUT}" | xclip -sel clip
fi
