#!/bin/bash

TOOLCHAINS_DIR="${WORKS_PATH}/android/toolchains"
TOOLCHAIN_BIN="aarch64-linux-android-"

if [ -z ${USE_CCACHE+x} ]; then
	TOOLCHAIN="aarch64-linux-android-4.9"
else
	if [ $USE_CCACHE -eq 1 ]; then
		TOOLCHAIN="ccache"
	else
		TOOLCHAIN="aarch64-linux-android-4.9"
	fi
fi

export CROSS_COMPILE="${TOOLCHAINS_DIR}/${TOOLCHAIN}/bin/${TOOLCHAIN_BIN}"
export CCACHE='ccache'

export KERNEL=$(pwd)
export ARCH=arm64
export SUBARCH=arm64
export KBUILD_BUILD_USER="thewisenerd"
export KBUILD_BUILD_HOST="eniac"

rm -rf std*.log

make "$@" # > >(tee stdout.log) 2> >(tee stderr.log >&2)
