#! /bin/bash

a=$( mktemp )
b=$( mktemp ).diff
c=$( mktemp ).diff

scripts/dtc/dtc -I dtb -O dts -s ./arch/arm/boot/dts/msm8939-mtp-smb1360-ferrari.dtb > ${a}

echo "cur vs xiaomz" > ${b}
diff -rupN "${a}" "/mnt/3369683a-a97e-4918-acbd-96ff82759ada/ferrari/dtbs/8.1.5.0/dt/msm8916-0005-sort.dts" >> ${b}

echo "cur vs old" > ${c}
diff -rupN /tmp/dtsold ${a} >> ${c}


mv ${a} /tmp/dtsold
geany ${b}
geany ${c}
