#! /bin/bash
mkaflash_ferrari;
#adb shell su -c 'reboot bootloader';
adb shell 'reboot bootloader';
fastboot flash boot $( find releases/ -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d" " ) && fastboot reboot
