#!/bin/bash

set -euo pipefail

CUR_DIR=$( pwd )

if [ ! -e ${CUR_DIR}/arch/arm64/boot/Image ]; then
  echo "no zImage found!";
  exit;
fi

if [ ! -d ${CUR_DIR}/releases/unpack ]; then
  echo "no working folder found!";
  exit;
fi

G_IDX=$( git rev-parse --verify --short HEAD )

dtbToolCM --force-v2 -o ${CUR_DIR}/releases/unpack/boot-dt -s 2048 -p scripts/dtc/ arch/arm/boot/

cp ${CUR_DIR}/arch/arm64/boot/Image ${CUR_DIR}/releases/unpack/boot-zImage

d=`date +%d%b%Y_%H%M%S`

OUT="boot_${d}_${G_IDX}.img"

echo ""
mkboot.1 -cf "${CUR_DIR}/releases/${OUT}" "${CUR_DIR}/releases/unpack"

if [ -z ${DISPLAY+x} ]; then
  echo -n "${CUR_DIR}/releases/${OUT}"
else
  echo -n "${CUR_DIR}/releases/${OUT}" | xclip -sel clip
fi
echo ""
