#!/bin/bash

CUR_DIR=$( pwd )

if [ ! -e ${CUR_DIR}/arch/arm64/boot/Image ]; then
  echo "no zImage found!";
  exit;
fi

if [ ! -d ${CUR_DIR}/releases/ ]; then
  echo "no working folder found!";
  exit;
fi

G_IDX=$( git rev-parse --verify --short HEAD )
G_DRT=
if [[ -n $(git status --porcelain) ]]; then G_DRT="-dirty"; fi

dtbToolCM --force-v2 -o ${CUR_DIR}/releases/unpack/dt.img -s 2048 -p scripts/dtc/ arch/arm64/boot/

cp ${CUR_DIR}/arch/arm64/boot/Image ${CUR_DIR}/releases/unpack/kernel

d=`date +%d%b%Y`

mkboot ${CUR_DIR}/releases/unpack ${CUR_DIR}/releases/boot_${d}_${G_IDX}${G_DRT}.img

echo OUTPUT: releases/boot_${d}_${G_IDX}${G_DRT}.img