#!/usr/bin/env bash

info "running prebootstrap"


npmrc() {
	rm -f "${DOTFILES_ROOT}/.npmrc.symlink"

	echo -e "prefix = ${WORKS_PATH}/.node" > "${DOTFILES_ROOT}/.npmrc.symlink"

	success "generated .npmrc"
}

npmrc
