#!/usr/bin/env bash

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

echo ''

# mpv-mpris
rm -rf /tmp/mpv-mpris
mkdir -p /tmp/mpv-mpris
cd /tmp/mpv-mpris
git clone https://github.com/hoyon/mpv-mpris.git .
make
make install
cd -
